// Field labels organized by section — shared between HiddenFieldsModal and TemplateBuilder
export const FIELD_SECTIONS: Record<string, Record<string, string>> = {
  'Property Address': {
    propertyNo: 'Property No.',
    block: 'Block',
    area: 'Area',
    city: 'City',
    wardVillageTaluka: 'Ward/Village/Taluka',
    subRegistryBlock: 'Sub-Registry/Block',
    district: 'District',
    nearbyLandmark: 'Nearby Landmark',
  },
  'Physical Characteristics': {
    landType: 'Land Type',
    accessApproach: 'Access/Approach',
    abutingRoads: 'Abutting Roads',
    plinthArea: 'Plinth Area',
    carpetArea: 'Carpet Area',
    saleableArea: 'Saleable Area',
  },
  'Boundaries': {
    northBoundary: 'North',
    southBoundary: 'South',
    eastBoundary: 'East',
    westBoundary: 'West',
    northEastBoundary: 'North-East',
    northWestBoundary: 'North-West',
    southEastBoundary: 'South-East',
    southWestBoundary: 'South-West',
  },
  'Property Classification': {
    propertyType: 'Property Type',
    localityClass: 'Locality Class',
    plotShape: 'Plot Shape',
    isLeasehold: 'Freehold/Leasehold',
    buildingOccupancy: 'Building Occupancy',
  },
  'Owner Details': {
    originalOwner: 'Original Owner',
    originalOwnerYear: 'Year of Ownership',
    ownerPhone: 'Phone Number',
    developerName: 'Developer Name',
    currentOwners: 'Current Owners',
  },
  'Valuation Parameters': {
    referenceNo: 'Reference No.',
    inspectionDate: 'Inspection Date',
    valuationDate: 'Valuation Date',
    valuationForDate: 'Valuation For Date',
    purpose: 'Purpose',
    plotArea: 'Plot Area',
    landRatePerSqm: 'Land Rate',
    landRateSource: 'Land Rate Source',
    locationIncreasePercent: 'Location Increase %',
    landShareFraction: 'Land Share Fraction',
    landShareDecimal: 'Land Share Decimal',
    floorArea: 'Floor Area',
    plinthAreaRate: 'Plinth Area Rate',
    costIndex: 'Cost Index',
    specificationIncreasePercent: 'Specification Increase %',
    yearOfConstruction: 'Year of Construction',
    estimatedLifeYears: 'Estimated Life',
    ageAtValuation: 'Age at Valuation',
  },
  'Building Specifications': {
    roof: 'Roof',
    brickwork: 'Brickwork',
    flooring: 'Flooring',
    tiles: 'Tiles',
    electrical: 'Electrical',
    electricalSwitches: 'Electrical Switches',
    sanitaryFixtures: 'Sanitary Fixtures',
    woodwork: 'Woodwork',
    exterior: 'Exterior',
  },
  'Technical Details': {
    floorHeight: 'Floor Height',
    constructionType: 'Construction Type',
    foundationType: 'Foundation Type',
    partitions: 'Partitions',
    roofingTerracing: 'Roofing & Terracing',
    architecturalFeatures: 'Architectural Features',
    noOfWaterClosets: 'No. of Water Closets',
    noOfSinks: 'No. of Sinks',
    sanitaryFittingsClass: 'Sanitary Fittings Class',
    compoundWallHeight: 'Compound Wall Height',
    compoundWallType: 'Compound Wall Type',
    overheadTank: 'Overhead Tank',
    noOfPumps: 'No. of Pumps',
    sewerDisposal: 'Sewer Disposal',
  },
  'Legal & Regulatory': {
    ownershipDocType: 'Ownership Document Type',
    occupancyCertificateStatus: 'OC Status',
    buildingPlanSanction: 'Building Plan Sanction',
    approvalAuthority: 'Approval Authority',
    planViolations: 'Plan Violations',
    unauthorizedConstructions: 'Unauthorized Constructions',
    farFsiPermitted: 'FAR/FSI Permitted',
    farFsiConsumed: 'FAR/FSI Consumed',
    groundCoverage: 'Ground Coverage',
    sarfaesiCompliant: 'SARFAESI Compliant',
    encumbrances: 'Encumbrances',
    heritageRestriction: 'Heritage Restriction',
  },
  'Infrastructure & Utilities': {
    waterSupply: 'Water Supply',
    sewerageSystem: 'Sewerage System',
    stormDrainage: 'Storm Drainage',
    solidWasteManagement: 'Solid Waste Management',
    electricityStatus: 'Electricity Status',
    publicTransportAccess: 'Public Transport Access',
  },
  'Environmental & Safety': {
    rainWaterHarvesting: 'Rain Water Harvesting',
    solarProvision: 'Solar Provision',
    greenBuildingFeatures: 'Green Building Features',
    environmentalPollution: 'Environmental Pollution',
    structuralSafety: 'Structural Safety',
    earthquakeResistance: 'Earthquake Resistance',
    visibleDamage: 'Visible Damage',
    firefightingProvision: 'Firefighting Provision',
    maintenanceIssues: 'Maintenance Issues',
    extentOfDeterioration: 'Extent of Deterioration',
  },
  'Economic & Rental': {
    reasonableLettingValue: 'Reasonable Letting Value',
    isOccupiedByTenant: 'Occupied by Tenant',
    numberOfTenants: 'Number of Tenants',
    tenancyDuration: 'Tenancy Duration',
    tenancyStatus: 'Tenancy Status',
    monthlyRent: 'Monthly Rent',
    propertyTaxStatus: 'Property Tax Status',
    propertyInsurance: 'Property Insurance',
    maintenanceCharges: 'Maintenance Charges',
    securityCharges: 'Security Charges',
  },
  'Marketability': {
    locationAttributes: 'Location Attributes',
    scarcityValue: 'Scarcity Value',
    demandSupplyComment: 'Demand & Supply',
    comparableSalePrices: 'Comparable Sale Prices',
    lastTwoTransactions: 'Last Two Transactions',
  },
  'Valuation Summary': {
    guidelineValueLand: 'Guideline Value - Land',
    guidelineValueBuilding: 'Guideline Value - Building',
    marketRateTrend: 'Market Rate Trend',
    forcedSaleValue: 'Forced Sale Value',
    insuranceValue: 'Insurance Value',
    valuationMethodology: 'Valuation Methodology',
    variationJustification: 'Variation Justification',
  },
};
